from __future__ import annotations

import stat
from pathlib import Path

import pytest

from zeta.project_memory_history import PROJECT_MEMORY_FILES
from zeta.project_registry import ProjectRegistry

MIRROR_HEADER = (
    "<!-- Generated by Zeta from the project memory store. Edits here are ignored "
    "and overwritten. Use /memory or `zeta project memory` to change memory. -->\n"
)


def _registry(tmp_path: Path, name: str = "projects") -> tuple[ProjectRegistry, str]:
    workspace = tmp_path / f"{name}-workspace"
    workspace.mkdir()
    registry = ProjectRegistry(tmp_path / name)
    project = registry.create_project(name, "scope", workspace)
    return registry, project.project_id


def _mirror_dir(registry: ProjectRegistry, project_id: str) -> Path:
    return registry.root / project_id / "memory"


def _assert_mirror_matches_current(
    registry: ProjectRegistry, project_id: str
) -> None:
    current = registry.memory_snapshot(project_id).contents
    mirror = _mirror_dir(registry, project_id)
    for name in PROJECT_MEMORY_FILES:
        assert mirror.joinpath(name).read_text(encoding="utf-8") == (
            MIRROR_HEADER + current[name]
        )


@pytest.mark.parametrize(
    "publish_kind", ["automatic", "manual", "undo", "accept", "remote-import"]
)
def test_mirror_reflects_current_version_after_each_publish(
    tmp_path: Path, publish_kind: str
) -> None:
    registry, project_id = _registry(tmp_path)

    if publish_kind == "automatic":
        snapshot = registry.memory_snapshot(project_id)
        registry.compare_and_swap_memory(
            project_id,
            expected_digest=snapshot.digest,
            updates={"state.md": "# Current state\n\nautomatic\n"},
            provenance={"session_id": "session", "seq_start": 1, "seq_end": 1},
        )
    elif publish_kind == "manual":
        registry.update_memory(project_id, {"state.md": "# Current state\n\nmanual\n"})
    elif publish_kind == "undo":
        snapshot = registry.memory_snapshot(project_id)
        registry.compare_and_swap_memory(
            project_id,
            expected_digest=snapshot.digest,
            updates={"state.md": "# Current state\n\nautomatic\n"},
            provenance={"session_id": "session", "seq_start": 1, "seq_end": 1},
        )
        registry.undo_memory(project_id)
    elif publish_kind == "accept":
        snapshot = registry.memory_snapshot(project_id)
        registry.compare_and_swap_memory(
            project_id,
            expected_digest=snapshot.digest,
            updates={"state.md": "# Current state\n\nautomatic\n"},
            provenance={"session_id": "session", "seq_start": 1, "seq_end": 1},
        )
        registry.accept_memory(project_id, "state.md")
    else:
        source, source_id = _registry(tmp_path, "source-projects")
        source.update_memory(source_id, {"state.md": "# Current state\n\nremote\n"})
        exported = source.export_memory(source_id)
        before = registry.memory_snapshot(project_id)
        registry.import_memory(
            project_id,
            exported,
            expected_digest=before.digest,
            provenance={"host": "remote"},
        )

    _assert_mirror_matches_current(registry, project_id)


def test_mirror_edits_are_ignored_and_overwritten(tmp_path: Path) -> None:
    registry, project_id = _registry(tmp_path)
    registry.update_memory(project_id, {"state.md": "# Current state\n\nauthoritative\n"})
    state_path = _mirror_dir(registry, project_id) / "state.md"
    state_path.chmod(0o600)
    state_path.write_text("# Current state\n\nlocal disk edit\n", encoding="utf-8")

    assert registry.memory_snapshot(project_id).contents["state.md"].endswith(
        "authoritative\n"
    )
    assert {
        item.name: item.content
        for item in registry.load_memory_for_context(project_id)
    }["state.md"].endswith("authoritative\n")
    assert registry.export_memory(project_id).contents["state.md"].endswith(
        "authoritative\n"
    )

    registry.update_memory(project_id, {"brief.md": "# Brief\n\nnext publish\n"})

    assert state_path.read_text(encoding="utf-8") == (
        MIRROR_HEADER + "# Current state\n\nauthoritative\n"
    )


def test_mirror_backfilled_for_stale_existing_store(tmp_path: Path) -> None:
    registry, project_id = _registry(tmp_path)
    registry.update_memory(project_id, {"state.md": "# Current state\n\ncurrent\n"})
    state_path = _mirror_dir(registry, project_id) / "state.md"
    state_path.chmod(0o600)
    state_path.write_text("# Current state\n\nstale\n", encoding="utf-8")

    registry.load_memory_for_context(project_id)

    assert state_path.read_text(encoding="utf-8") == (
        MIRROR_HEADER + "# Current state\n\ncurrent\n"
    )
    inodes = {
        name: _mirror_dir(registry, project_id).joinpath(name).stat().st_ino
        for name in PROJECT_MEMORY_FILES
    }

    registry.load_memory_for_context(project_id)

    assert {
        name: _mirror_dir(registry, project_id).joinpath(name).stat().st_ino
        for name in PROJECT_MEMORY_FILES
    } == inodes


def test_mirror_files_are_read_only_and_atomic(tmp_path: Path) -> None:
    registry, project_id = _registry(tmp_path)
    registry.update_memory(project_id, {"state.md": "# Current state\n\nfirst\n"})
    mirror = _mirror_dir(registry, project_id)

    assert {
        stat.S_IMODE(mirror.joinpath(name).stat().st_mode)
        for name in PROJECT_MEMORY_FILES
    } == {0o400}

    outside = tmp_path / "outside.md"
    outside.write_text("do not replace\n", encoding="utf-8")
    state_path = mirror / "state.md"
    state_path.unlink()
    state_path.symlink_to(outside)

    registry.update_memory(project_id, {"brief.md": "# Brief\n\nsecond\n"})

    assert not state_path.is_symlink()
    assert state_path.read_text(encoding="utf-8").endswith("first\n")
    assert outside.read_text(encoding="utf-8") == "do not replace\n"
    assert not [path for path in mirror.iterdir() if path.name.endswith(".tmp")]


def test_mirror_header_never_enters_store_prompt_or_export(tmp_path: Path) -> None:
    registry, project_id = _registry(tmp_path)
    content = "# Current state\n\nstore only\n"
    registry.update_memory(project_id, {"state.md": content})

    assert registry.memory_snapshot(project_id).contents["state.md"] == content
    assert {
        item.name: item.content
        for item in registry.load_memory_for_context(project_id)
    }["state.md"] == content
    assert registry.export_memory(project_id).contents["state.md"] == content
    assert MIRROR_HEADER.strip() not in str(registry.memory_log(project_id))


def test_legacy_migration_still_reads_md_without_store(tmp_path: Path) -> None:
    registry, project_id = _registry(tmp_path)
    state_path = _mirror_dir(registry, project_id) / "state.md"
    legacy = "# Current state\n\nlegacy input\n"
    state_path.write_text(legacy, encoding="utf-8")

    assert registry.memory_snapshot(project_id).contents["state.md"] == legacy

    registry.update_memory(project_id, {"brief.md": "# Brief\n\nmigrated\n"})

    assert registry.memory_snapshot(project_id).contents["state.md"] == legacy
    assert state_path.read_text(encoding="utf-8") == MIRROR_HEADER + legacy
