"""Human and structured read models for dormant format-2 project memory.

This module is the view seam for mirrors, tools, the CLI, and serve. Callers pass
one validated snapshot and do not need to understand entry lifecycle rules.
"""

from __future__ import annotations

import dataclasses
import json
from collections.abc import Iterable, Mapping

from zeta.memory.entry_store import MemoryEntry, MemoryState

GENERATED_MIRROR_HEADER = (
    "<!-- Generated by Zeta from the project memory store. Edits here are ignored "
    "and overwritten. Use /memory or `zeta project memory` to change memory. -->\n"
)


def _accepted(entry: MemoryEntry) -> bool:
    return not entry.automatic or entry.accepted_at is not None


def active_entries(state: MemoryState, *, kind: str | None = None) -> list[MemoryEntry]:
    """Return active entries in stable schema, date, and ID order."""
    order = {item.key: index for index, item in enumerate(state.schema.kinds)}
    entries = [
        entry
        for entry in state.entries.values()
        if isinstance(entry, MemoryEntry)
        and entry.status == "active"
        and (kind is None or entry.kind == kind)
    ]
    return sorted(entries, key=lambda item: (order[item.kind], item.created_at, item.id))


def render_kind(state: MemoryState, kind_key: str) -> str:
    """Render one schema kind without the generated-file header."""
    kind = next((item for item in state.schema.kinds if item.key == kind_key), None)
    if kind is None:
        raise ValueError(f"unknown memory kind: {kind_key}")
    entries = active_entries(state, kind=kind_key)
    accepted = [entry for entry in entries if _accepted(entry)]
    automatic = [entry for entry in entries if not _accepted(entry)]
    lines = [f"# {kind.name}", ""]
    for heading, values in (("Accepted", accepted), ("Automatic", automatic)):
        lines.extend((f"## {heading}", ""))
        if not values:
            lines.extend(("_None._", ""))
            continue
        for entry in values:
            date = entry.seen_at[:10] if heading == "Automatic" else entry.updated_at[:10]
            label = f"seen {date}" if heading == "Automatic" else date
            lines.append(f"- `{entry.id}` ({label}) {entry.text}")
        lines.append("")
    return "\n".join(lines)


def render_all_kinds(state: MemoryState) -> dict[str, str]:
    return {kind.key: render_kind(state, kind.key) for kind in state.schema.kinds}


def entry_value(entry: MemoryEntry) -> dict[str, object]:
    value = dataclasses.asdict(entry)
    value["sources"] = [dataclasses.asdict(source) for source in entry.sources]
    return value


def inspect_value(
    state: MemoryState,
    *,
    inactive_limit: int = 100,
    byte_cap: int | None = None,
) -> dict[str, object]:
    """Return current entry data, optionally fitted to a strict JSON byte cap."""
    active = active_entries(state)
    inactive = sorted(
        (
            entry
            for entry in state.entries.values()
            if isinstance(entry, MemoryEntry) and entry.status != "active"
        ),
        key=lambda item: (item.updated_at, item.id),
        reverse=True,
    )[:inactive_limit]
    result: dict[str, object] = {
        "format": 2,
        "generation": state.generation,
        "schema": dataclasses.asdict(state.schema),
        "entries": [],
        "entries_truncated": False,
        "inactive": [
            {
                "id": entry.id,
                "kind": entry.kind,
                "status": entry.status,
                "updated_at": entry.updated_at,
                "superseded_by": list(entry.superseded_by),
            }
            for entry in inactive
        ],
    }
    values = [entry_value(entry) for entry in active]
    if byte_cap is None:
        result["entries"] = values
        return result
    if type(byte_cap) is not int or byte_cap < 1024:
        raise ValueError("memory view byte cap is too small")
    while _json_size(result) > byte_cap and result["inactive"]:
        result["inactive"].pop()  # type: ignore[union-attr]
    selected: list[dict[str, object]] = []
    result["entries"] = selected
    for value in values:
        selected.append(value)
        if _json_size(result) > byte_cap:
            selected.pop()
            break
    if len(selected) < len(values):
        result["entries_truncated"] = True
    return result


def _json_size(value: object) -> int:
    return len(json.dumps(value, separators=(",", ":"), ensure_ascii=False).encode())


def kind_views(state: MemoryState) -> list[dict[str, object]]:
    """Return the formatted, count-bearing serve overview."""
    result: list[dict[str, object]] = []
    for kind in state.schema.kinds:
        entries = active_entries(state, kind=kind.key)
        result.append(
            {
                "key": kind.key,
                "name": kind.name,
                "description": kind.description,
                "active_count": len(entries),
                "automatic_count": sum(not _accepted(entry) for entry in entries),
                "accepted_count": sum(_accepted(entry) for entry in entries),
                "rendered": render_kind(state, kind.key),
                "rendered_truncated": False,
            }
        )
    return result


def receipt_touches(record: Mapping[str, object], entry_id: str) -> bool:
    operations = record.get("operations", ())
    return isinstance(operations, Iterable) and any(
        isinstance(operation, Mapping)
        and entry_id
        in (*operation.get("target_ids", ()), *operation.get("result_ids", ()))
        for operation in operations
    )


__all__ = [
    "active_entries",
    "entry_value",
    "inspect_value",
    "kind_views",
    "receipt_touches",
    "render_all_kinds",
    "render_kind",
]
